name: OWASP ZAP DAST Scan

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  zap_scan:
    name: Run ZAP DAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build
        run: docker build -t insecure-web-app .

      - name: Start app
        run: |
          docker run -d --name web-app -p 5000:5000 insecure-web-app
          sleep 10

      - name: Zap output folder
        run: |
          mkdir -p zap-output
          chmod 777 zap-output 

      - name: Run Scan
        run: |
          docker run --network host --rm \
            -v ${{ github.workspace  }}/zap-output:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t http://localhost:5000 \
            -a \
            -r zap-report.html
    

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: zap-output/zap-report.html

      - name: Cleanup
        if: always()
        run: docker rm -f web-app || true
